# curl -X POST "http://127.0.0.1:8000/ai-suggest/" \
#   -H "Content-Type: application/json" \
#   -d '{"prompt":"Suggest me a good electric SUV under $50,000","budget":50000,"needs":"electric SUV"}'


# curl -s -X POST "http://127.0.0.1:8000/compare-cars/" \
#   -H "Content-Type: application/json" \
#   -d '{"car1":"Tesla Model 3 2025","car2":"BMW 1974"}' \
# | jq

# curl -s -X POST "http://127.0.0.1:8000/analyze-cars/" \
#   -H "Content-Type: application/json" \
#   -d '[{"title":"Tesla Model 3 2025","brand":"Tesla","year_numeric":2025,"mileage_numeric":12000,"price_numeric":42000,"is_premium":1,"age":0}]' \
# | jq

curl -X POST http://127.0.0.1:8000/ai-suggest/ \
-H "Content-Type: application/json" \
-d '{
  "stage": 3
}'

